apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: {{ .Values.namespace }}
  labels: {{- include "task-manager.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.db.database | quote }}
  POSTGRES_USER: {{ .Values.db.username | quote }}
